sed -i "s/matlab建模.png/matlab_modeling.png/g" `grep matlab建模.png -rl ./`
sed -i "s/Matlab输出扭矩.jpg/matlab_output_torque.jpg/g" `grep Matlab输出扭矩.jpg -rl ./`
sed -i "s/ROS环境搭建.jpg/ros_environment_setup.jpg/g" `grep ROS环境搭建.jpg -rl ./`
sed -i "s/不同长度三杆组合分析.jpg/analysis_of_three-par_combinations_of_different_lengths.jpg/g" `grep 不同长度三杆组合分析.jpg -rl ./`
sed -i "s/切应力.png/shear_stress.png/g" `grep 切应力.png -rl ./`
sed -i "s/拉伸位移.png/tensile_displacement.png/g" `grep 拉伸位移.png -rl ./`
sed -i "s/改进前正应力.png/normal_stress_before_improvement.png/g" `grep 改进前正应力.png -rl ./`
sed -i "s/正应力.jpg/normal_stress.jpg/g" `grep 正应力.jpg -rl ./`
sed -i "s/蜗杆的应力与扭矩.png/stress_and_torque_of_worm.png/g" `grep 蜗杆的应力与扭矩.png -rl ./`
sed -i "s/software_analysising.tex/software_analysising.tex/g" `grep software_analysising.tex -rl ./`
