sed -i "s/上机架横板.png/Upper_rack_horizontal_plate.png/g" `grep 上机架横板.png -rl ./`
sed -i "s/下机架横板.png/Under_rack_cross_plate.png/g" `grep 下机架横板.png -rl ./`
sed -i "s/下部传动模块.png/Lower_transmission_module.png/g" `grep 下部传动模块.png -rl ./`
sed -i "s/五杆机构.png/Five-bar_mechanism.png/g" `grep 五杆机构.png -rl ./`
sed -i "s/五杆机构构件1.png/Five-bar_mechanism_component_1.png/g" `grep 五杆机构构件1.png -rl ./`
sed -i "s/五杆机构构件2.png/Five-bar_mechanism_component_2.png/g" `grep 五杆机构构件2.png -rl ./`
sed -i "s/五杆机构构件3.png/Five-bar_mechanism_component_3.png/g" `grep 五杆机构构件3.png -rl ./`
sed -i "s/五杆机构构件4.png/Five-bar_mechanism_component_4.png/g" `grep 五杆机构构件4.png -rl ./`
sed -i "s/伞齿轮.JPG/Bevel_gear.JPG/g" `grep 伞齿轮.JPG -rl ./`
sed -i "s/扭簧.JPG/Torsion_spring.JPG/g" `grep 扭簧.JPG -rl ./`
sed -i "s/换向夹取模块.png/Reversing_clamping_module.png/g" `grep 换向夹取模块.png -rl ./`
sed -i "s/末端执行机构总览.png/Overview_of_end_effectors.png/g" `grep 末端执行机构总览.png -rl ./`
sed -i "s/机架竖板.png/Rack_riser.png/g" `grep 机架竖板.png -rl ./`
sed -i "s/水平伞齿轮轴1.png/Horizontal_bevel_gear_shaft_1.png/g" `grep 水平伞齿轮轴1.png -rl ./`
sed -i "s/水平伞齿轮轴2.png/Horizontal_bevel_gear_shaft_2.png/g" `grep 水平伞齿轮轴2.png -rl ./`
sed -i "s/电机外接竖轴.png/Motor_external_vertical_shaft.png/g" `grep 电机外接竖轴.png -rl ./`
sed -i "s/直齿轮.png/Spur_gear.png/g" `grep 直齿轮.png -rl ./`
sed -i "s/竖伞齿轮轴.png/Shaft_gear_shaft.png/g" `grep 竖伞齿轮轴.png -rl ./`
